### ISSUE TITLE
Waiting until the keyword appears in the title may not be enough

### ISSUE THREAD

**Issue by sbmzhcn** [NikolaiT/GoogleScraper#46]
scraping.py line 900
```python
# Waiting until the keyword appears in the title may
# not be enough. The content may still be from the old page.
try:
    WebDriverWait(self.webdriver, 5).until(EC.title_contains(self.current_keyword))
except TimeoutException as e:
    logger.error(SeleniumSearchError('Keyword "{}" not found in title: {}'.format(self.current_keyword, self.webdriver.title)))
    break
```
like search engine ask.com, the title is always "Ask.com - What&#39;s Your Question?" . So i suggest determine url param .

**Comment by sbmzhcn** [comment]
```python
# first move mouse to the next element, some times the element is not visibility, like blekko.com
WebDriverWait(self.webdriver, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR, selector)))
next_element = self.webdriver.find_element_by_css_selector(selector)
webdriver.ActionChains(self.webdriver).move_to_element(next_element).perform()
# wait until the next page link emerges
WebDriverWait(self.webdriver, 15).until(EC.visibility_of_element_located((By.CSS_SELECTOR, selector)))
element = self.webdriver.find_element_by_css_selector(selector)
```

**Comment by NikolaiT** [comment]
I don't know. I mean there is not a good generic solution to go to the next results page for every search engine, because search engines are fundamentally different.

+ For example with blekko.com, there are many different kinds of results, and one needs to simulate a real user (moving the mouse like you mentioned) to get the next results.
+ With ask.com the search query is not in the title.

To solve this issue, the next page behaviour should also be abstracted in a own class for every search engine. 

+ Default method to determine that the next keyword was loaded: It can can be found in the title.
+ Default method to go to next page: Press next page link.

Solution is similar to parsing: Just use a own class for all the search engines that are different from the base cases...

**Comment by sbmzhcn** [comment]
wait_until_keyword_in_url
can replace with
`wait_until_keyword_in_url`
 and
`WebDriverWait(self.webdriver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, selector)))`

because, when the keywords in url, but the page is not loaded.  but for the all SE,   when the next pageselector is presence,  the page source is loaded.

**Comment by NikolaiT** [comment]
Ok sorry for the long waiting time. Now the default strategy is as you proposed:

When the SE supports a next pageselector, then ```wait_until_serp_loaded``` checks if such a link is available.
