### ISSUE TITLE
can you support use google ip to scrape ?

### ISSUE THREAD

**Issue by sbmzhcn** [NikolaiT/GoogleScraper#52]
i know google have thousands of ip, `216.58.209.154` , `74.125.198.199`

can you let the program support use google's ip to scrape ?

http://216.58.209.154/search

**Comment by NikolaiT** [comment]
This is quite tricky because it's not obvious which keyword should be scraped with which google ip address?

I tought about introducing a special keyword-file format:

**Format:**
```
"keyword " search_engine search_engine_url number_of_pages proxy 
```

**Example:**
```
"love is good " google "http://216.58.209.154/search" 5 socks5:localhost:9050
"love is bad " yahoo "yahoo.com" 11 http:11.22.33.44:5433
"love may be good " bing "http://56.32.111.154/search" 5 socks4:localhost:80
```

This is very good, because you can control the scraping process very easy. Also, it is very simple to create such a keyword file with any scripting language [Python].

What do you think?

**Comment by sbmzhcn** [comment]
i think that's a good idea.  keywords file should be easy.

when use google, form google_ips.txt get random ip, and then set google base_url random.

**Comment by NikolaiT** [comment]
Fixed but currently not working. Filed a report on https://github.com/kennethreitz/requests/issues/2404

**Comment by sbmzhcn** [comment]
request with different ip have another method:
http://stackoverflow.com/questions/1150332/source-interface-with-python-and-urllib2

In C#, i know you can set http proxy with google ip, and then the request url is the same. but requsted ip is another.

**Comment by NikolaiT** [comment]
Now works with **http-mode**. Closing issue.
